### ISSUE TITLE
Strange Vertical Sparklines

### ISSUE THREAD

**Issue by mvberg** [elysiumphase/node-sparkline#11]
Hi @adrienv1520 - Thanks for this lib!

I'm noticing some datasets generate just vertical lines and not a true sparkline .. 

Here is the input, logs and output: https://gist.github.com/mvberg/19adb148a6ffdd0b86bfd31aad2ced4e

The same values render OK on [quickchart.io](https://quickchart.io/chart?c={type:%27sparkline%27,data:{datasets:[{data:[%228.766%22,%229.109%22,%229.056%22,%229.131%22,%229.164%22,%229.285%22,%229.18%22,%229.062%22,%229.152%22,%229.204%22,%229.32%22,%229.277%22,%229.406%22,%229.266%22,%229.387%22,%229.505%22,%2210.038%22,%2210.152%22,%2210.04%22,%2210.044%22,%229.719%22,%229.464%22,%229.533%22,%229.346%22,%229.383%22,%228.872%22,%228.847%22,%228.972%22,%228.968%22,%229.068%22,%228.964%22,%229.045%22,%229.192%22,%229.185%22,%229.256%22,%229.293%22,%229.607%22,%229.575%22,%229.348%22,%229.236%22,%228.815%22,%228.937%22,%229.018%22,%228.977%22,%229.124%22,%229.242%22,%229.314%22,%229.359%22,%229.187%22,%229.418%22,%229.301%22,%229.183%22,%229.147%22,%229.198%22,%229.093%22,%229.271%22,%229.159%22,%229.286%22,%229.223%22,%229.395%22,%229.084%22,%229.12%22,%229.165%22,%229.196%22,%229.294%22,%228.966%22,%229.206%22,%229.191%22,%229.029%22,%229.1%22,%229.04%22,%229.098%22,%228.929%22,%229%22,%229.042%22,%229.037%22,%229.16%22,%229.254%22,%229.246%22,%229.266%22,%229.408%22,%229.576%22,%229.542%22,%229.452%22,%229.365%22,%229.411%22,%229.434%22,%229.45%22,%229.369%22,%229.48%22,%229.467%22,%229.466%22,%229.568%22,%229.564%22,%229.678%22,%229.955%22,%229.868%22,%2210.133%22,%2210.125%22,%2210.11%22,%229.962%22,%229.913%22,%229.822%22,%229.741%22,%229.334%22,%229.278%22,%229.248%22,%229.184%22,%229.056%22,%229.043%22,%229.07%22,%229.114%22,%229.072%22,%229.134%22,%229.231%22,%229.312%22,%229.464%22,%229.518%22,%229.421%22,%229.604%22,%229.568%22,%229.708%22,%229.713%22,%229.682%22,%229.63%22,%229.594%22,%229.594%22,%229.614%22,%229.942%22,%229.861%22,%229.941%22,%229.908%22,%229.897%22,%229.839%22,%229.845%22,%2210.036%22,%229.968%22,%229.899%22,%2210.03%22,%229.895%22,%2210.056%22,%2210.128%22,%2210.096%22,%2210.14%22,%2210.395%22,%2210.302%22,%2210.243%22,%2210.387%22,%2210.301%22,%2210.178%22,%2210.146%22,%2210.048%22,%2210.029%22,%2210.128%22,%229.929%22,%229.934%22,%229.959%22,%229.922%22,%229.929%22,%229.938%22,%229.905%22,%229.831%22,%229.914%22,%2210%22,%229.966%22,%229.944%22,%229.686%22,%229.469%22,%229.335%22,%229.334%22,%229.53%22,%229.487%22,%229.458%22,%229.539%22,%229.741%22,%229.751%22,%229.526%22,%229.567%22,%229.599%22,%229.528%22,%229.469%22,%229.618%22,%229.694%22,%229.728%22,%229.673%22,%229.597%22,%229.592%22,%229.536%22]}]}}) ..

Any ideas?

**Comment by alternatiph** [comment]
@mvberg I have created a PR for this issue(#13) , meanwhile you can direct npm to our repo to fix this.
i.e.: `"node-sparkline": "github:Bitex-Platform/node-sparkline",`

**Comment by mvberg** [comment]
fantastic, thanks @alternatiph - will take a look!

**Comment by adrienv1520** [comment]
Sorry for the delay, will have a look quickly. Thanks for your help.
